---
# I think that name is ambiguous - is it the name of the user or the machine - so change to host!
 - host: mach-1
   user: js5
   tywl;qkel;wq
   size: 16G
 - host: mach-2
 wkqejmkl;wqekjk;
   type: ubuntu
   size: 8G
 - host: mach-3
   usqlwjehlwjkqe
   type: osx
   size: 16G
